# Site settings
title: TeacherGreencow
email: mattiaswickberg[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site about web and programming by a teacher in language and communication. Also opera (not the browser).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: TeacherGreencow
github_username:  mattiaswickberg

# Build settings
markdown: kramdown
